### PR TITLE
Add format options for all CLPlacename attributes

### PR DESCRIPTION
**Pull request by KR4DIO**

### CODE REVIEW

**Comment by fulldecent** [comment]
Thank you. I'm having trouble reviewing this now because I can't get this to build with the latest Xcode. It is having trouble with linking.

**Comment by KR4DIO** [comment]
That's strange -- it builds fine on my 10.14.4 system with XCode 10.2.

**Comment by fulldecent** [comment]
I updated and it is working well now. Thank you.

Can you please update the `-help` documentation for these new options. Then it is good to go.

**Comment by KR4DIO** [comment]
Ok, I updated the `-h` documentation and fixed a bug I hadn't noticed (%time was evaluated before %timeZone)

**Comment by fulldecent** [comment]
Looks great, thank you, merging

**Comment by fulldecent** [comment]
Attempting to release to homebrew cask. Tracking that here https://github.com/Homebrew/homebrew-cask/issues/61587

**Pull request merged**
